### PR TITLE
#81 Tests for OnMoon\OpenApiServerBundle\Exception

### LINKED ISSUE #81: Tests for OnMoon\OpenApiServerBundle\Exception
Cover the OnMoon\OpenApiServerBundle\Exception namespace with unit tests

### PR DESCRIPTION
**Pull request by Miraell**
Closes #81

### CODE REVIEW

File: test/unit/Exception/OpenApiErrorTest.php [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+
+namespace OnMoon\OpenApiServerBundle\Test\Unit\Exception;
+
+use OnMoon\OpenApiServerBundle\Exception\OpenApiError;
+use PHPUnit\Framework\TestCase;
+
+/**
+ * @covers \OnMoon\OpenApiServerBundle\Exception\OpenApiError
+ */
+final class OpenApiErrorTest extends TestCase
```
Comment (sspat) [inline test/unit/Exception/OpenApiErrorTest.php:13]: This test can be skipped at all, the subject class adds no new behavior to the base exception class

File: test/unit/Exception/CannotParseOpenApiTest.php [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+{
+    public function testCannotParseOpenApi(): void
+    {
+        $cannotParseOpenApiException = CannotParseOpenApi::becauseNoOperationIdSpecified([
+            'method' => 'testMethod',
+            'url' => 'testUrl',
+            'path' => 'testPath',
+        ]);
+
+        $this->expectException(CannotParseOpenApi::class);
```
Comment (sspat) [inline test/unit/Exception/CannotParseOpenApiTest.php:23]: This test should verify the messages of the exceptions created by all the named constructors of the class

File: test/unit/Exception/ApiCallFailedTest.php [hunk 3]
```diff
@@ -0,0 +1,22 @@
...
+
+/**
+ * @covers \OnMoon\OpenApiServerBundle\Exception\ApiCallFailed
+ */
+final class ApiCallFailedTest extends TestCase
+{
+    public function testApiCallFailedBecauseNotImplementedPrintsInterface(): void
+    {
+        $this->expectException(ApiCallFailed::class);
+        $this->expectExceptionMessage('testInterfaceName');
```
Comment (sspat) [inline test/unit/Exception/ApiCallFailedTest.php:18]: The full exception message should be checked, e.g.
Api call implementation not found. Please implement "testInterfaceName" interface

File: test/unit/Exception/ApiCallFailedTest.php [hunk 4]
```diff
@@ -0,0 +1,22 @@
...
+
+namespace OnMoon\OpenApiServerBundle\Test\Unit\Exception;
+
+use OnMoon\OpenApiServerBundle\Exception\ApiCallFailed;
+use PHPUnit\Framework\TestCase;
+
+/**
+ * @covers \OnMoon\OpenApiServerBundle\Exception\ApiCallFailed
+ */
+final class ApiCallFailedTest extends TestCase
```
Comment (sspat) [inline test/unit/Exception/ApiCallFailedTest.php:13]: Not all methods are tested
https://coveralls.io/builds/32500345/source?filename=src/Exception/ApiCallFailed.php

File: test/unit/Exception/CannotParseOpenApiTest.php [hunk 5]
```diff
@@ -0,0 +1,167 @@
...
+use PHPUnit\Framework\TestCase;
+
+use function Safe\sprintf;
+
+/**
+ * @covers \OnMoon\OpenApiServerBundle\Exception\CannotParseOpenApi
+ */
+final class CannotParseOpenApiTest extends TestCase
+{
+    public function tesBecauseNoOperationIdSpecifiedShowsCorrectErrorMessage(): void
```
Comment (sspat) [inline test/unit/Exception/CannotParseOpenApiTest.php:17]: This method is not executed because of a typo in the method name.
Please check coverage report
https://coveralls.io/builds/32500345/source?filename=src/Exception/CannotParseOpenApi.php
